import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed. Use GET.' });
  }

  const tools = [
    {
      name: 'show_hello',
      title: 'Show hello widget',
      description: 'Returns the hello widget and (optionally) a greeting generated by the OpenAI SDK.'
    },
    {
      name: 'agile_get_snapshot',
      title: 'Get ServiceNow Agile Snapshot',
      description: 'Fetches the current sprint with all stories and scrum tasks from ServiceNow. Returns aggregated data including sprint info, stories, tasks, and assignees.'
    },
    {
      name: 'agile_update_task_state',
      title: 'Update ServiceNow Task State',
      description: 'Updates the state of a ServiceNow scrum task (rm_scrum_task). Accepts either a task sys_id OR task number (e.g., \'STSK0011008\') and a state label (e.g., \'Draft\', \'Ready\', \'Work in Progress\', \'Complete\', \'Cancelled\').'
    },
    {
      name: 'agile_get_task_details',
      title: 'Get Task Details',
      description: 'Returns detailed task data for a scrum task, including attachments and activity. Accepts either a task sys_id OR task number (e.g., \'STSK0011008\').'
    },
    {
      name: 'sn_query',
      title: 'Query ServiceNow Records',
      description: 'Query ServiceNow table records with filtering, pagination, and field selection',
      parameters: ['table (required)', 'query', 'limit', 'offset', 'fields']
    },
    {
      name: 'sn_get',
      title: 'Get ServiceNow Record',
      description: 'Retrieve a single ServiceNow record by sys_id',
      parameters: ['table (required)', 'sys_id (required)']
    },
    {
      name: 'sn_create',
      title: 'Create ServiceNow Record',
      description: 'Create a new record in a ServiceNow table',
      parameters: ['table (required)', 'data (required)']
    },
    {
      name: 'sn_update',
      title: 'Update ServiceNow Record',
      description: 'Update an existing ServiceNow record',
      parameters: ['table (required)', 'sys_id (required)', 'data (required)']
    },
    {
      name: 'sn_delete',
      title: 'Delete ServiceNow Record',
      description: 'Delete a ServiceNow record (requires confirm: true)',
      parameters: ['table (required)', 'sys_id (required)', 'confirm (required)']
    },
    {
      name: 'sn_aggregate',
      title: 'Aggregate ServiceNow Data',
      description: 'Perform aggregation operations (COUNT, SUM, AVG, MIN, MAX) on ServiceNow tables',
      parameters: ['table (required)', 'operation (required)', 'field', 'query', 'groupBy']
    },
    {
      name: 'sn_schema',
      title: 'Get ServiceNow Table Schema',
      description: 'Get the schema definition for a ServiceNow table',
      parameters: ['table (required)']
    },
    {
      name: 'sn_discover',
      title: 'Discover ServiceNow Tables',
      description: 'Discover available ServiceNow tables',
      parameters: ['filter']
    },
    {
      name: 'sn_relationships',
      title: 'Get CMDB Relationships',
      description: 'Get CMDB relationships for a configuration item',
      parameters: ['ci_sys_id (required)', 'depth']
    },
    {
      name: 'sn_syslog',
      title: 'Query System Logs',
      description: 'Query ServiceNow system logs',
      parameters: ['query', 'limit']
    },
    {
      name: 'sn_attachments',
      title: 'List Attachments',
      description: 'List attachments for a specific record',
      parameters: ['table (required)', 'record_id (required)']
    }
  ];

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ServiceNow MCP Tools</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 40px 20px;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    header {
      text-align: center;
      color: white;
      margin-bottom: 40px;
    }
    h1 {
      font-size: 2.5rem;
      margin-bottom: 10px;
      text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
    }
    .subtitle {
      font-size: 1.1rem;
      opacity: 0.9;
    }
    .stats {
      display: flex;
      gap: 20px;
      justify-content: center;
      margin: 30px 0;
      flex-wrap: wrap;
    }
    .stat-card {
      background: white;
      padding: 20px 40px;
      border-radius: 12px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .stat-number {
      font-size: 2.5rem;
      font-weight: bold;
      color: #667eea;
    }
    .stat-label {
      color: #666;
      font-size: 0.9rem;
      margin-top: 5px;
    }
    .tools-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
      gap: 20px;
    }
    .tool-card {
      background: white;
      border-radius: 12px;
      padding: 24px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
      transition: transform 0.2s, box-shadow 0.2s;
    }
    .tool-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 8px 12px rgba(0,0,0,0.15);
    }
    .tool-name {
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 0.9rem;
      color: #667eea;
      background: #f0f0ff;
      padding: 6px 12px;
      border-radius: 6px;
      display: inline-block;
      margin-bottom: 12px;
      font-weight: 600;
    }
    .tool-title {
      font-size: 1.3rem;
      font-weight: 600;
      color: #333;
      margin-bottom: 8px;
    }
    .tool-description {
      color: #666;
      line-height: 1.6;
      margin-bottom: 12px;
    }
    .tool-params {
      font-size: 0.85rem;
      color: #888;
      margin-top: 12px;
      padding-top: 12px;
      border-top: 1px solid #eee;
    }
    .category-header {
      color: white;
      font-size: 1.5rem;
      margin: 40px 0 20px 0;
      padding-bottom: 10px;
      border-bottom: 2px solid rgba(255,255,255,0.3);
    }
    .endpoint-info {
      background: rgba(255,255,255,0.1);
      color: white;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 30px;
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 0.9rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🚀 ServiceNow MCP Server</h1>
      <p class="subtitle">Model Context Protocol Tools for ServiceNow Integration</p>
    </header>

    <div class="stats">
      <div class="stat-card">
        <div class="stat-number">${tools.length}</div>
        <div class="stat-label">Total Tools</div>
      </div>
      <div class="stat-card">
        <div class="stat-number">4</div>
        <div class="stat-label">Agile Tools</div>
      </div>
      <div class="stat-card">
        <div class="stat-number">11</div>
        <div class="stat-label">CRUD Tools</div>
      </div>
    </div>

    <div class="endpoint-info">
      <strong>MCP Endpoint:</strong> https://servicenow-mcp2.vercel.app/api/mcp
    </div>

    <h2 class="category-header">⚡ Agile & Sprint Management Tools</h2>
    <div class="tools-grid">
      ${tools.slice(0, 4).map(tool => `
        <div class="tool-card">
          <div class="tool-name">${tool.name}</div>
          <div class="tool-title">${tool.title}</div>
          <div class="tool-description">${tool.description}</div>
          ${tool.parameters ? `<div class="tool-params"><strong>Parameters:</strong> ${tool.parameters.join(', ')}</div>` : ''}
        </div>
      `).join('')}
    </div>

    <h2 class="category-header">🔧 ServiceNow CRUD & Analytics Tools</h2>
    <div class="tools-grid">
      ${tools.slice(4).map(tool => `
        <div class="tool-card">
          <div class="tool-name">${tool.name}</div>
          <div class="tool-title">${tool.title}</div>
          <div class="tool-description">${tool.description}</div>
          ${tool.parameters ? `<div class="tool-params"><strong>Parameters:</strong> ${tool.parameters.join(', ')}</div>` : ''}
        </div>
      `).join('')}
    </div>
  </div>
</body>
</html>
  `;

  res.setHeader('Content-Type', 'text/html');
  res.status(200).send(html);
}
