import type { NextApiRequest, NextApiResponse } from "next";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import OpenAI from "openai";
import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createClientFromEnv } from "../../../lib/servicenow/client";
import { getAgileSnapshot } from "../../../lib/servicenow/agileSnapshot";
import { getStateValue, getAllStateChoices } from "../../../lib/servicenow/stateMapping";
import { getTaskDetails } from "../../../lib/servicenow/taskDetails";

export const config = {
  api: {
    bodyParser: false
  }
};

const MCP_METHODS = new Set(["POST", "GET", "DELETE"]);
const WIDGET_URI = "ui://widget/hello.html";
const widgetPath = path.join(process.cwd(), "public", "widget", "index.html");

function loadWidgetHtml() {
  if (!existsSync(widgetPath)) {
    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello Widget</title>
  </head>
  <body>
    <div style="padding:24px;font-family:system-ui">Run <code>npm run build:widget</code> to generate the React widget.</div>
  </body>
</html>`;
  }

  return readFileSync(widgetPath, "utf8");
}

function createHelloServer() {
  const server = new McpServer({ name: "hello-world", version: "0.1.0" });
  const widgetHtml = loadWidgetHtml();

  server.registerResource("hello-widget", WIDGET_URI, {}, async () => ({
    contents: [
      {
        uri: WIDGET_URI,
        mimeType: "text/html+skybridge",
        text: widgetHtml,
        _meta: { "openai/widgetPrefersBorder": false }
      }
    ]
  }));

  const openai = process.env.OPENAI_API_KEY
    ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
    : null;

  server.registerTool(
    "show_hello",
    {
      title: "Show hello widget",
      description:
        "Returns the hello widget and (optionally) a greeting generated by the OpenAI SDK.",
      inputSchema: z.object({
        use_model: z.boolean().optional()
      }),
      _meta: {
        "openai/outputTemplate": WIDGET_URI,
        "openai/toolInvocation/invoking": "Showing Hello World",
        "openai/toolInvocation/invoked": "Hello World ready"
      }
    },
    async (args) => {
      let greeting = "Hello World";

      if (args?.use_model && openai) {
        const model = process.env.OPENAI_MODEL || "gpt-5";
        const response = await openai.responses.create({
          model,
          input: "Say 'Hello World' as a short greeting."
        });

        const text = response.output_text?.trim();
        if (text) {
          greeting = text;
        }
      }

      return {
        content: [{ type: "text", text: greeting }],
        structuredContent: { greeting }
      };
    }
  );

  // ServiceNow Agile Tool: Get current sprint snapshot
  server.registerTool(
    "agile_get_snapshot",
    {
      title: "Get ServiceNow Agile Snapshot",
      description:
        "Fetches the current sprint with all stories and scrum tasks from ServiceNow. Returns aggregated data including sprint info, stories, tasks, and assignees.",
      inputSchema: z.object({}),
      _meta: {
        "openai/toolInvocation/invoking": "Fetching sprint data from ServiceNow",
        "openai/toolInvocation/invoked": "Sprint snapshot retrieved"
      }
    },
    async () => {
      try {
        const client = createClientFromEnv();
        
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { 
              ok: false, 
              error: "ServiceNow credentials not configured" 
            }
          };
        }

        const snapshot = await getAgileSnapshot(client);
        
        const storyCount = snapshot.stories.length;
        const taskCount = snapshot.stories.reduce((sum, story) => sum + story.tasks.length, 0);
        const sprintName = snapshot.sprint?.name || "No current sprint";
        
        return {
          content: [{ 
            type: "text", 
            text: `Retrieved sprint "${sprintName}" with ${storyCount} stories and ${taskCount} tasks` 
          }],
          structuredContent: { snapshot }
        };
      } catch (error: any) {
        console.error('[MCP agile_get_snapshot] Error:', error);
        return {
          content: [{ type: "text", text: `Failed to fetch snapshot: ${error.message}` }],
          structuredContent: { 
            ok: false, 
            error: error.message || "Unknown error" 
          }
        };
      }
    }
  );

  // ServiceNow Agile Tool: Update task state
  server.registerTool(
    "agile_update_task_state",
    {
      title: "Update ServiceNow Task State",
      description:
        "Updates the state of a ServiceNow scrum task (rm_scrum_task). Accepts either a task sys_id OR task number (e.g., 'STSK0011008') and a state label (e.g., 'Draft', 'Ready', 'Work in Progress', 'Complete', 'Cancelled'). The state label is automatically mapped to the correct numeric choice value.",
      inputSchema: z.object({
        taskId: z.string().optional(),
        taskKey: z.string().optional(),
        state: z.string().min(1, "State is required")
      }).refine(
        (data) => data.taskId || data.taskKey,
        { message: "Either taskId or taskKey is required" }
      ),
      _meta: {
        "openai/toolInvocation/invoking": "Updating task state in ServiceNow",
        "openai/toolInvocation/invoked": "Task state updated"
      }
    },
    async (args) => {
      try {
        const { taskId, taskKey, state } = args;

        const client = createClientFromEnv();
        
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { 
              ok: false, 
              error: "ServiceNow credentials not configured" 
            }
          };
        }

        // Resolve sys_id from taskKey if needed
        let resolvedTaskId = taskId;
        
        if (!resolvedTaskId && taskKey) {
          console.log(`[MCP agile_update_task_state] Looking up sys_id for task key: ${taskKey}`);
          
          try {
            const lookupResponse = await client.query<{ sys_id: { value: string } }>(
              'rm_scrum_task',
              {
                sysparm_query: `number=${taskKey}`,
                sysparm_fields: 'sys_id',
                sysparm_limit: '1'
              }
            );

            if (!lookupResponse.result || lookupResponse.result.length === 0) {
              console.error(`[MCP agile_update_task_state] Task not found for key: ${taskKey}`);
              return {
                content: [{ 
                  type: "text", 
                  text: `Task not found for key "${taskKey}"` 
                }],
                structuredContent: { 
                  ok: false, 
                  error: "Task not found for key",
                  taskKey
                }
              };
            }

            resolvedTaskId = lookupResponse.result[0].sys_id.value;
            console.log(`[MCP agile_update_task_state] Resolved ${taskKey} to sys_id: ${resolvedTaskId}`);
          } catch (lookupError: any) {
            console.error(`[MCP agile_update_task_state] Lookup error:`, lookupError);
            return {
              content: [{ 
                type: "text", 
                text: `Failed to lookup task key "${taskKey}": ${lookupError.message}` 
              }],
              structuredContent: { 
                ok: false, 
                error: `Failed to lookup task key: ${lookupError.message}`,
                taskKey
              }
            };
          }
        }

        const taskIdentifier = taskKey || taskId;
        console.log(`[MCP agile_update_task_state] Updating task ${taskIdentifier} (sys_id: ${resolvedTaskId}) to state: ${state}`);

        // Map state label to numeric choice value (with caching)
        const stateValue = await getStateValue(client, state);

        if (!stateValue) {
          // Fetch all available choices for error message
          const allChoices = await getAllStateChoices(client);
          const allowedLabels = allChoices.map(c => c.label);
          
          console.error(`[MCP agile_update_task_state] Could not map state "${state}"`);
          console.error('[MCP agile_update_task_state] Available choices:', allChoices);
          
          return {
            content: [{ 
              type: "text", 
              text: `Could not map state "${state}". Allowed states: ${allowedLabels.join(', ')}` 
            }],
            structuredContent: { 
              ok: false, 
              error: `Could not map state "${state}"`,
              allowedStates: allowedLabels
            }
          };
        }

        console.log(`[MCP agile_update_task_state] Mapped "${state}" to value: "${stateValue}"`);

        // PATCH the task in ServiceNow
        await client.patch('rm_scrum_task', resolvedTaskId!, {
          state: stateValue
        });

        console.log(`[MCP agile_update_task_state] Successfully updated task ${taskIdentifier}`);

        return {
          content: [{ 
            type: "text", 
            text: `Successfully updated task ${taskIdentifier} to state "${state}"` 
          }],
          structuredContent: { 
            ok: true,
            taskId: resolvedTaskId,
            taskKey: taskKey || undefined,
            state,
            stateValue
          }
        };
      } catch (error: any) {
        console.error('[MCP agile_update_task_state] Error:', error);
        return {
          content: [{ 
            type: "text", 
            text: `Failed to update task: ${error.message}` 
          }],
          structuredContent: { 
            ok: false, 
            error: error.message || "Unknown error" 
          }
        };
      }
    }
  );

  // ServiceNow Agile Tool: Get task details
  server.registerTool(
    "agile_get_task_details",
    {
      title: "Get Task Details",
      description:
        "Returns detailed task data for a scrum task, including attachments and activity. Accepts either a task sys_id OR task number (e.g., 'STSK0011008').",
      inputSchema: z.object({
        taskId: z.string().optional(),
        taskKey: z.string().optional()
      }).refine(
        (data) => Boolean(data.taskId) !== Boolean(data.taskKey),
        { message: "Provide exactly one of taskId or taskKey" }
      ),
      _meta: {
        "openai/toolInvocation/invoking": "Fetching task details from ServiceNow",
        "openai/toolInvocation/invoked": "Task details retrieved"
      }
    },
    async (args) => {
      try {
        const { taskId, taskKey } = args;

        const client = createClientFromEnv();
        
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { 
              ok: false, 
              error: "ServiceNow credentials not configured" 
            }
          };
        }

        console.log(`[MCP agile_get_task_details] Fetching task details for ${taskKey || taskId}`);

        // Call the aggregator with ServiceNow client
        const task = await getTaskDetails(client, { taskId, taskKey });

        console.log(`[MCP agile_get_task_details] Successfully loaded task: ${task.key}`);

        return {
          content: [{ 
            type: "text", 
            text: `Loaded task details for ${task.key}: "${task.title}"` 
          }],
          structuredContent: { task }
        };
      } catch (error: any) {
        console.error('[MCP agile_get_task_details] Error:', error);
        return {
          content: [{ 
            type: "text", 
            text: `Failed to fetch task details: ${error.message}` 
          }],
          structuredContent: { 
            ok: false, 
            error: error.message || "Unknown error" 
          }
        };
      }
    }
  );

  // ServiceNow CRUD Tools
  server.registerTool(
    "sn_query",
    {
      title: "Query ServiceNow Records",
      description: "Query ServiceNow table records with filtering, pagination, and field selection",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name to query"),
        query: z.string().optional().describe("Encoded query string for filtering"),
        limit: z.number().optional().default(100).describe("Maximum number of records to return"),
        offset: z.number().optional().describe("Number of records to skip"),
        fields: z.string().optional().describe("Comma-separated list of fields to return")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const params: Record<string, string> = {
          sysparm_limit: String(args.limit)
        };
        if (args.query) params.sysparm_query = args.query;
        if (args.offset) params.sysparm_offset = String(args.offset);
        if (args.fields) params.sysparm_fields = args.fields;

        const result = await client.query(args.table, params);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: result
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Query failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_get",
    {
      title: "Get ServiceNow Record",
      description: "Retrieve a single ServiceNow record by sys_id",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name"),
        sys_id: z.string().describe("The sys_id of the record to retrieve")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.get(args.table, args.sys_id);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: result
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Get failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_create",
    {
      title: "Create ServiceNow Record",
      description: "Create a new record in a ServiceNow table",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name"),
        data: z.record(z.any()).describe("The data for the new record")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.create(args.table, args.data);

        return {
          content: [{ type: "text", text: `Record created successfully:\n${JSON.stringify(result, null, 2)}` }],
          structuredContent: result
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Create failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_update",
    {
      title: "Update ServiceNow Record",
      description: "Update an existing ServiceNow record",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name"),
        sys_id: z.string().describe("The sys_id of the record to update"),
        data: z.record(z.any()).describe("The fields to update")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.update(args.table, args.sys_id, args.data);

        return {
          content: [{ type: "text", text: `Record updated successfully:\n${JSON.stringify(result, null, 2)}` }],
          structuredContent: result
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Update failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_delete",
    {
      title: "Delete ServiceNow Record",
      description: "Delete a ServiceNow record (requires confirm: true)",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name"),
        sys_id: z.string().describe("The sys_id of the record to delete"),
        confirm: z.boolean().describe("Must be true to confirm deletion")
      })
    },
    async (args) => {
      try {
        if (!args.confirm) {
          return {
            content: [{ type: "text", text: "Delete operation requires confirm: true" }],
            structuredContent: { ok: false, error: "Delete operation requires confirm: true" }
          };
        }

        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        await client.delete(args.table, args.sys_id);

        return {
          content: [{ type: "text", text: `Record ${args.sys_id} deleted successfully from ${args.table}` }],
          structuredContent: { ok: true, message: "Record deleted successfully" }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Delete failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_aggregate",
    {
      title: "Aggregate ServiceNow Data",
      description: "Perform aggregation operations (COUNT, SUM, AVG, MIN, MAX) on ServiceNow tables",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name"),
        operation: z.enum(['COUNT', 'SUM', 'AVG', 'MIN', 'MAX']).describe("Aggregation operation"),
        field: z.string().optional().describe("Field to aggregate (required for SUM, AVG, MIN, MAX)"),
        query: z.string().optional().describe("Encoded query string for filtering"),
        groupBy: z.string().optional().describe("Field to group results by")
      })
    },
    async (args) => {
      try {
        if (args.operation !== 'COUNT' && !args.field) {
          return {
            content: [{ type: "text", text: `Field is required for ${args.operation} operation` }],
            structuredContent: { ok: false, error: `Field is required for ${args.operation} operation` }
          };
        }

        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.aggregate(args.table, args.query, args.groupBy, args.operation, args.field);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: { result }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Aggregate failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_schema",
    {
      title: "Get ServiceNow Table Schema",
      description: "Get the schema definition for a ServiceNow table",
      inputSchema: z.object({
        table: z.string().describe("The ServiceNow table name to get schema for")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.getSchema(args.table);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: result
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Schema retrieval failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_discover",
    {
      title: "Discover ServiceNow Tables",
      description: "Discover available ServiceNow tables",
      inputSchema: z.object({
        filter: z.string().optional().describe("Filter tables by name or label")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.discoverTables(args.filter);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: { tables: result }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Discover failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_relationships",
    {
      title: "Get CMDB Relationships",
      description: "Get CMDB relationships for a configuration item",
      inputSchema: z.object({
        ci_sys_id: z.string().describe("Configuration Item sys_id"),
        depth: z.number().optional().default(3).describe("Depth of relationship traversal")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.getRelationships(args.ci_sys_id, args.depth);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: { result }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Relationships retrieval failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_syslog",
    {
      title: "Query System Logs",
      description: "Query ServiceNow system logs",
      inputSchema: z.object({
        query: z.string().optional().describe("Encoded query string for filtering logs"),
        limit: z.number().optional().default(100).describe("Maximum number of log entries")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.getSystemLogs(args.query, args.limit);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: { logs: result }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `System logs retrieval failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  server.registerTool(
    "sn_attachments",
    {
      title: "List Attachments",
      description: "List attachments for a specific record",
      inputSchema: z.object({
        table: z.string().describe("Table name"),
        record_id: z.string().describe("Record sys_id")
      })
    },
    async (args) => {
      try {
        const client = createClientFromEnv();
        if (!client) {
          return {
            content: [{ type: "text", text: "ServiceNow client not configured" }],
            structuredContent: { ok: false, error: "ServiceNow credentials not configured" }
          };
        }

        const result = await client.getAttachments(args.table, args.record_id);

        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
          structuredContent: { attachments: result }
        };
      } catch (error: any) {
        return {
          content: [{ type: "text", text: `Attachments retrieval failed: ${error.message}` }],
          structuredContent: { ok: false, error: error.message }
        };
      }
    }
  );

  return server;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
      "Access-Control-Allow-Headers": "content-type, mcp-session-id",
      "Access-Control-Expose-Headers": "Mcp-Session-Id"
    });
    res.end();
    return;
  }

  if (!req.method || !MCP_METHODS.has(req.method)) {
    res.status(405).send("Method Not Allowed");
    return;
  }

  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Expose-Headers", "Mcp-Session-Id");

  const server = createHelloServer();
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true
  });

  res.on("close", () => {
    transport.close();
    server.close();
  });

  try {
    await server.connect(transport);
    await transport.handleRequest(req, res);
  } catch (error) {
    console.error("Error handling MCP request:", error);
    if (!res.headersSent) {
      res.status(500).send("Internal server error");
    }
  }
}
